import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runCommand } from "./helpers.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "../..");
const serverRoot = path.join(repoRoot, "apps", "fact-server");

test("server e2e: jwt and jwks utilities", async (t) => {
  const keysDir = fs.mkdtempSync(path.join(os.tmpdir(), "fact-e2e-jwt-jwks-"));
  const sqliteDbRelativePath = path.join(
    "tmp",
    `e2e-jwt-jwks-${Date.now()}-${Math.random().toString(16).slice(2)}.sqlite3`,
  );
  const sqliteDbAbsolutePath = path.join(repoRoot, sqliteDbRelativePath);
  const tokenEncryptionKey = "e2e-token-coverage-key";

  t.after(() => {
    fs.rmSync(keysDir, { recursive: true, force: true });
    fs.rmSync(sqliteDbAbsolutePath, { force: true });
  });

  const script = [
    "import assert from 'node:assert/strict';",
    "import jwt from 'jsonwebtoken';",
    "import passport from 'passport';",
    "import { initializeDb, createSchema, getDb } from './src/db/schema.ts';",
    "import logger, { log } from './src/logger.ts';",
    "import {",
    "  initializeJWKS,",
    "  getCurrentPrivateKey,",
    "  getCurrentKeyId,",
    "  getPublicJWKS,",
    "  getKeyById,",
    "  getAllValidKeys,",
    "  rotateKeysManually,",
    "  cleanupJWKS,",
    "  isJWKSInitialized,",
    "} from './src/auth/jwks.ts';",
    "import {",
    "  encryptToken,",
    "  decryptToken,",
    "  revokeToken,",
    "  isTokenRevoked,",
    "  revokeAllUserTokens,",
    "  cleanupExpiredBlacklistedTokens,",
    "  generateJWT,",
    "  verifyJWT,",
    "  refreshAccessToken,",
    "  generateState,",
    "  validateState,",
    "  generateOAuthStateJWT,",
    "  verifyOAuthStateJWT,",
    "  initializePassportJWTStrategy,",
    "  initializePassportSerialization,",
    "} from './src/auth/jwt.ts';",
    "",
    "const originalFetch = global.fetch;",
    "const originalNow = Date.now;",
    "",
    "try {",
    "  await initializeDb();",
    "  await createSchema(getDb());",
    "  const db = getDb();",
    "",
    "  assert.equal(isJWKSInitialized(), false);",
    "  initializeJWKS();",
    "  assert.equal(isJWKSInitialized(), true);",
    "",
    "  const firstKid = getCurrentKeyId();",
    "  assert.ok(firstKid);",
    "  assert.ok(getCurrentPrivateKey());",
    "  assert.ok(getKeyById(firstKid));",
    "  assert.equal(getKeyById('missing-kid'), null);",
    "  assert.ok(getAllValidKeys().length >= 1);",
    "",
    "  const jwksBeforeRotate = getPublicJWKS();",
    "  assert.ok(Array.isArray(jwksBeforeRotate.keys));",
    "  assert.ok(jwksBeforeRotate.keys.length >= 1);",
    "",
    "  rotateKeysManually();",
    "  const secondKid = getCurrentKeyId();",
    "  assert.ok(secondKid);",
    "  assert.notEqual(secondKid, firstKid);",
    "",
    "  const jwksAfterRotate = getPublicJWKS();",
    "  assert.ok(jwksAfterRotate.keys.some((key) => key.kid === secondKid));",
    "  assert.ok(getKeyById(firstKid));",
    "  assert.equal(new Set(jwksAfterRotate.keys.map((key) => key.kid)).size, jwksAfterRotate.keys.length);",
    "  for (const key of jwksAfterRotate.keys) {",
    "    assert.equal(key.kty, 'RSA');",
    "    assert.equal(key.use, 'sig');",
    "    assert.equal(key.alg, 'RS256');",
    "    assert.equal(typeof key.n, 'string');",
    "    assert.equal(typeof key.e, 'string');",
    "    assert.equal('d' in key, false);",
    "    assert.equal('p' in key, false);",
    "    assert.equal('q' in key, false);",
    "    assert.equal('dp' in key, false);",
    "    assert.equal('dq' in key, false);",
    "    assert.equal('qi' in key, false);",
    "  }",
    "",
    "  const encrypted = encryptToken(JSON.stringify({ accessToken: 'a1', refreshToken: 'r1' }));",
    "  const decrypted = decryptToken(encrypted);",
    "  assert.equal(decrypted, JSON.stringify({ accessToken: 'a1', refreshToken: 'r1' }));",
    "  assert.throws(() => decryptToken('not-a-token'), /Failed to decrypt token/);",
    "",
    "  const discordUser = {",
    "    type: 'discord',",
    "    id: 'jwt-user-1',",
    "    username: 'jwt-user',",
    "    avatar: null,",
    "    discriminator: null,",
    "    guild: 'guild-1',",
    "    hasRole: true,",
    "    isAdmin: false,",
    "    devBypass: false,",
    "    encryptedTokens: encrypted,",
    "    expires: Date.now() + 60_000,",
    "    scope: 'identify guilds',",
    "    cacheUpdatedAt: Date.now(),",
    "    lastCheck: Date.now(),",
    "    cachedGuildIds: ['guild-1'],",
    "    cachedMemberRoles: ['role-1'],",
    "  };",
    "",
    "  const discordToken = generateJWT(discordUser);",
    "  const verifiedDiscord = verifyJWT(discordToken);",
    "  assert.equal(verifiedDiscord?.type, 'discord');",
    "  assert.equal(verifiedDiscord?.id, discordUser.id);",
    "  assert.equal(verifiedDiscord?.accessToken, 'a1');",
    "  assert.equal(verifiedDiscord?.refreshToken, 'r1');",
    "",
    "  const devUser = {",
    "    type: 'dev',",
    "    id: 'dev-user-1',",
    "    username: 'dev-user',",
    "    avatar: null,",
    "    discriminator: null,",
    "    guild: null,",
    "    hasRole: true,",
    "    isAdmin: true,",
    "    devBypass: true,",
    "  };",
    "",
    "  const devToken = generateJWT(devUser);",
    "  const verifiedDev = verifyJWT(devToken);",
    "  assert.equal(verifiedDev?.type, 'dev');",
    "  assert.equal(verifiedDev?.id, devUser.id);",
    "",
    "  assert.equal(verifyJWT('bad.jwt.token'), null);",
    "",
    "  const noKidToken = jwt.sign({ sub: 'user-no-kid' }, getCurrentPrivateKey(), { algorithm: 'RS256', expiresIn: '1h' });",
    "  assert.equal(verifyJWT(noKidToken), null);",
    "",
    "  const unknownKidToken = jwt.sign({ sub: 'user-unknown-kid' }, getCurrentPrivateKey(), { algorithm: 'RS256', keyid: 'unknown-kid', expiresIn: '1h' });",
    "  assert.equal(verifyJWT(unknownKidToken), null);",
    "",
    "  const noSubToken = jwt.sign({ username: 'no-sub' }, getCurrentPrivateKey(), { algorithm: 'RS256', keyid: getCurrentKeyId(), expiresIn: '1h' });",
    "  assert.equal(verifyJWT(noSubToken), null);",
    "",
    "  const badEncryptedToken = jwt.sign({ sub: 'discord-bad-enc', username: 'bad-enc', hasRole: true, isAdmin: false, devBypass: false, encryptedTokens: 'bad.encrypted.format' }, getCurrentPrivateKey(), { algorithm: 'RS256', keyid: getCurrentKeyId(), expiresIn: '1h' });",
    "  const badEncryptedVerified = verifyJWT(badEncryptedToken);",
    "  assert.equal(badEncryptedVerified?.type, 'discord');",
    "",
    "  const currentKid = getCurrentKeyId();",
    "  const publicKeyPem = getKeyById(currentKid)?.export({ format: 'pem', type: 'spki' }).toString();",
    "  assert.ok(publicKeyPem);",
    "",
    "  const hsConfusionToken = jwt.sign({ sub: 'hs-confusion-user' }, publicKeyPem, { algorithm: 'HS256', keyid: currentKid, expiresIn: '1h' });",
    "  assert.equal(verifyJWT(hsConfusionToken), null);",
    "",
    "  const noneHeader = Buffer.from(JSON.stringify({ alg: 'none', typ: 'JWT', kid: currentKid })).toString('base64url');",
    "  const nonePayload = Buffer.from(JSON.stringify({ sub: 'none-user' })).toString('base64url');",
    "  const algNoneToken = `${noneHeader}.${nonePayload}.`;",
    "  assert.equal(verifyJWT(algNoneToken), null);",
    "",
    "  const futureNbfToken = jwt.sign({ sub: 'future-nbf', nbf: Math.floor(Date.now() / 1000) + 3600 }, getCurrentPrivateKey(), { algorithm: 'RS256', keyid: currentKid, expiresIn: '2h' });",
    "  assert.equal(verifyJWT(futureNbfToken), null);",
    "",
    "  const expiredAccessToken = jwt.sign({ sub: 'expired-access' }, getCurrentPrivateKey(), { algorithm: 'RS256', keyid: currentKid, expiresIn: '-1s' });",
    "  assert.equal(verifyJWT(expiredAccessToken), null);",
    "",
    "  const tokenParts = discordToken.split('.');",
    "  const originalPayload = JSON.parse(Buffer.from(tokenParts[1], 'base64url').toString('utf8'));",
    "  const tamperedPayload = Buffer.from(JSON.stringify({ ...originalPayload, isAdmin: true })).toString('base64url');",
    "  const tamperedToken = `${tokenParts[0]}.${tamperedPayload}.${tokenParts[2]}`;",
    "  assert.equal(verifyJWT(tamperedToken), null);",
    "",
    "  const refreshUser = { ...discordUser, refreshToken: 'refresh-1', scope: 'identify' };",
    "",
    "  global.fetch = async () => ({",
    "    ok: true,",
    "    status: 200,",
    "    headers: new Headers(),",
    "    json: async () => ({ access_token: 'new-access', refresh_token: 'new-refresh', expires_in: 120, scope: 'identify guilds' }),",
    "    text: async () => '',",
    "  });",
    "  const refreshed = await refreshAccessToken(refreshUser);",
    "  assert.equal(refreshed.accessToken, 'new-access');",
    "  assert.equal(refreshed.refreshToken, 'new-refresh');",
    "",
    "  global.fetch = async () => ({",
    "    ok: false,",
    "    status: 429,",
    "    headers: new Headers({ 'retry-after': '2' }),",
    "    text: async () => 'rate limit',",
    "  });",
    "  await assert.rejects(() => refreshAccessToken(refreshUser), /rate limit/i);",
    "",
    "  global.fetch = async () => ({",
    "    ok: false,",
    "    status: 500,",
    "    headers: new Headers(),",
    "    text: async () => 'boom',",
    "  });",
    "  await assert.rejects(() => refreshAccessToken(refreshUser), /Failed to refresh token/);",
    "",
    "  global.fetch = async () => ({",
    "    ok: true,",
    "    status: 200,",
    "    headers: new Headers(),",
    "    json: async () => ({ refresh_token: 'only-refresh' }),",
    "    text: async () => '',",
    "  });",
    "  await assert.rejects(() => refreshAccessToken(refreshUser), /access_token missing/);",
    "",
    "  const devRefresh = await refreshAccessToken(devUser);",
    "  assert.deepEqual(devRefresh, { devBypass: true });",
    "  await assert.rejects(() => refreshAccessToken({ ...discordUser, refreshToken: undefined }), /No refresh token available/);",
    "  await assert.rejects(() => refreshAccessToken({ type: 'custom', id: 'x', username: 'x' }), /Invalid user type/);",
    "",
    "  assert.equal(validateState('missing-state'), false);",
    "  const state = generateState();",
    "  assert.equal(validateState(state), true);",
    "  assert.equal(validateState(state), false);",
    "",
    "  Date.now = () => 1_000_000;",
    "  const expiredState = generateState();",
    "  Date.now = () => 1_000_000 + 11 * 60 * 1000;",
    "  assert.equal(validateState(expiredState), false);",
    "  Date.now = originalNow;",
    "",
    "  const stateJwt = generateOAuthStateJWT();",
    "  const verifiedStateJwt = verifyOAuthStateJWT(stateJwt);",
    "  assert.equal(verifiedStateJwt?.type, 'oauth_state');",
    "",
    "  const noKidStateJwt = jwt.sign({ type: 'oauth_state', nonce: 'n1' }, getCurrentPrivateKey(), { algorithm: 'RS256', expiresIn: '10m' });",
    "  assert.equal(verifyOAuthStateJWT(noKidStateJwt), null);",
    "",
    "  const unknownKidStateJwt = jwt.sign({ type: 'oauth_state', nonce: 'n2' }, getCurrentPrivateKey(), { algorithm: 'RS256', keyid: 'unknown-kid', expiresIn: '10m' });",
    "  assert.equal(verifyOAuthStateJWT(unknownKidStateJwt), null);",
    "",
    "  const wrongTypeStateJwt = jwt.sign({ type: 'not_oauth_state', nonce: 'n3' }, getCurrentPrivateKey(), { algorithm: 'RS256', keyid: getCurrentKeyId(), expiresIn: '10m' });",
    "  assert.equal(verifyOAuthStateJWT(wrongTypeStateJwt), null);",
    "",
    "  const hsStateJwt = jwt.sign({ type: 'oauth_state', nonce: 'n-hs' }, publicKeyPem, { algorithm: 'HS256', keyid: getCurrentKeyId(), expiresIn: '10m' });",
    "  assert.equal(verifyOAuthStateJWT(hsStateJwt), null);",
    "",
    "  const noneStateHeader = Buffer.from(JSON.stringify({ alg: 'none', typ: 'JWT', kid: getCurrentKeyId() })).toString('base64url');",
    "  const noneStatePayload = Buffer.from(JSON.stringify({ type: 'oauth_state', nonce: 'n-none' })).toString('base64url');",
    "  const noneStateJwt = `${noneStateHeader}.${noneStatePayload}.`;",
    "  assert.equal(verifyOAuthStateJWT(noneStateJwt), null);",
    "",
    "  const expiredStateJwt = jwt.sign({ type: 'oauth_state', nonce: 'n4' }, getCurrentPrivateKey(), { algorithm: 'RS256', keyid: getCurrentKeyId(), expiresIn: '-1s' });",
    "  assert.equal(verifyOAuthStateJWT(expiredStateJwt), null);",
    "",
    "  assert.equal(verifyOAuthStateJWT('not-a-jwt'), null);",
    "",
    "  initializePassportJWTStrategy();",
    "  initializePassportSerialization();",
    "  const jwtStrategy = passport._strategies?.jwt;",
    "  assert.ok(jwtStrategy);",
    "  const verifyStrategy = jwtStrategy._verify || jwtStrategy.verify;",
    "  assert.equal(typeof verifyStrategy, 'function');",
    "",
    "  await new Promise((resolve, reject) => {",
    "    verifyStrategy({ sub: 'discord-strategy', username: 'discord', devBypass: false, hasRole: true, isAdmin: false }, (err, user) => {",
    "      if (err) return reject(err);",
    "      try {",
    "        assert.equal(user?.type, 'discord');",
    "        assert.equal(user?.id, 'discord-strategy');",
    "      } catch (assertErr) {",
    "        return reject(assertErr);",
    "      }",
    "      resolve();",
    "    });",
    "  });",
    "",
    "  await new Promise((resolve, reject) => {",
    "    verifyStrategy({ sub: 'dev-strategy', username: 'dev', devBypass: true, hasRole: true, isAdmin: true }, (err, user) => {",
    "      if (err) return reject(err);",
    "      try {",
    "        assert.equal(user?.type, 'dev');",
    "        assert.equal(user?.id, 'dev-strategy');",
    "      } catch (assertErr) {",
    "        return reject(assertErr);",
    "      }",
    "      resolve();",
    "    });",
    "  });",
    "",
    "  await new Promise((resolve, reject) => {",
    "    const badPayload = {};",
    "    Object.defineProperty(badPayload, 'sub', {",
    "      configurable: true,",
    "      enumerable: true,",
    "      get() {",
    "        throw new Error('payload boom');",
    "      },",
    "    });",
    "    verifyStrategy(badPayload, (_err, user) => {",
    "      try {",
    "        assert.equal(user, false);",
    "      } catch (assertErr) {",
    "        return reject(assertErr);",
    "      }",
    "      resolve();",
    "    });",
    "  });",
    "",
    "  log('info', 'coverage-info', { k: 'v' });",
    "  log('warn', 'coverage-warn');",
    "  log('error', 'coverage-error', new Error('coverage boom'));",
    "  log('debug', 'coverage-debug', null);",
    "  log('info');",
    "  log('warn');",
    "  log('error');",
    "  log('debug');",
    "  const circular = {};",
    "  circular.self = circular;",
    "  log('debug', circular);",
    "",
    "  const req = {",
    "    method: 'GET',",
    "    originalUrl: '/coverage/request-logger',",
    "    ip: '127.0.0.1',",
    "    authStatus: { authenticated: true },",
    "    get(header) {",
    "      return header.toLowerCase() === 'user-agent' ? 'e2e-agent' : undefined;",
    "    },",
    "  };",
    "  let finishHandler = null;",
    "  const res = {",
    "    headersSent: false,",
    "    statusCode: 204,",
    "    on(event, cb) {",
    "      if (event === 'finish') finishHandler = cb;",
    "    },",
    "    status(code) {",
    "      this.statusCode = code;",
    "      return this;",
    "    },",
    "    json(payload) {",
    "      this.payload = payload;",
    "      return this;",
    "    },",
    "  };",
    "",
    "  let requestNextCalled = false;",
    "  logger.requestLogger(req, res, () => {",
    "    requestNextCalled = true;",
    "  });",
    "  assert.equal(requestNextCalled, true);",
    "  assert.equal(typeof finishHandler, 'function');",
    "  finishHandler();",
    "",
    "  const errorRes = {",
    "    headersSent: false,",
    "    statusCode: 200,",
    "    status(code) {",
    "      this.statusCode = code;",
    "      return this;",
    "    },",
    "    json(payload) {",
    "      this.payload = payload;",
    "      return this;",
    "    },",
    "  };",
    "  let errorNextCalled = false;",
    "  logger.errorHandler(new Error('handler failure'), req, errorRes, () => {",
    "    errorNextCalled = true;",
    "  });",
    "  assert.equal(errorRes.statusCode, 500);",
    "  assert.equal(errorRes.payload?.error, 'Internal Server Error');",
    "  assert.equal(errorNextCalled, true);",
    "",
    "  const alreadySentRes = {",
    "    headersSent: true,",
    "    statusCode: 204,",
    "    status(code) {",
    "      this.statusCode = code;",
    "      return this;",
    "    },",
    "    json(payload) {",
    "      this.payload = payload;",
    "      return this;",
    "    },",
    "  };",
    "  logger.errorHandler('string-error', req, alreadySentRes, () => {});",
    "  assert.equal(alreadySentRes.statusCode, 204);",
    "",
    "  await db.insertInto('users').values({ discord_name: 'jwt-user-1', email: 'jwt-user-1@example.com' }).execute();",
    "  const nowSeconds = Math.floor(Date.now() / 1000);",
    "  await revokeToken('jti-valid-1', 'jwt-user-1', nowSeconds + 300, 'coverage');",
    "  assert.equal(await isTokenRevoked('jti-valid-1'), true);",
    "  assert.equal(await isTokenRevoked('jti-unknown-1'), false);",
    "  assert.equal(await revokeAllUserTokens('jwt-user-1', 'coverage'), 1);",
    "  assert.equal(await revokeAllUserTokens('missing-user', 'coverage'), 0);",
    "  await revokeToken('jti-expired-1', 'jwt-user-1', nowSeconds - 10, 'expired');",
    "  const cleanupCount = await cleanupExpiredBlacklistedTokens();",
    "  assert.ok(Number(cleanupCount) >= 0);",
    "  await db.schema.dropTable('jwt_token_blacklist').execute();",
    "  assert.equal(await isTokenRevoked('jti-db-error-fail-closed'), true);",
    "  await assert.rejects(() => revokeToken('jti-db-error-fail-closed', 'jwt-user-1', nowSeconds + 300), /.+/);",
    "",
    "  cleanupJWKS();",
    "  initializeJWKS();",
    "  cleanupJWKS();",
    "",
    "  console.log('E2E_JWT_JWKS_OK');",
    "} finally {",
    "  Date.now = originalNow;",
    "  global.fetch = originalFetch;",
    "  cleanupJWKS();",
    "}",
  ].join("\n");

  const firstRun = await runCommand(
    "node",
    ["-r", "tsconfig-paths/register", "-r", "@swc-node/register", "-e", script],
    {
      cwd: serverRoot,
      env: {
        ...process.env,
        NODE_ENV: "development",
        TOKEN_ENCRYPTION_KEY: tokenEncryptionKey,
        KEYS_DIR: keysDir,
        SQLITE_DB: sqliteDbRelativePath,
        ENABLE_FEDERATION: "false",
        ENABLE_FEDERATION_PROVIDER: "false",
        ENABLE_FEDERATION_LOGIN: "false",
      },
    },
  );

  assert.equal(firstRun.code, 0, `JWT/JWKS script failed\n${firstRun.output}`);
  assert.match(firstRun.output, /E2E_JWT_JWKS_OK/, `Expected success marker\n${firstRun.output}`);

  const keysFilePath = path.join(keysDir, "keys.json");
  if (fs.existsSync(keysFilePath)) {
    fs.chmodSync(keysDir, 0o777);
    fs.chmodSync(keysFilePath, 0o666);
  }

  const reloadScript = [
    "import assert from 'node:assert/strict';",
    "import { initializeJWKS, getPublicJWKS, cleanupJWKS, isJWKSInitialized } from './src/auth/jwks.ts';",
    "initializeJWKS();",
    "assert.equal(isJWKSInitialized(), true);",
    "const publicKeys = getPublicJWKS();",
    "assert.ok(Array.isArray(publicKeys.keys));",
    "assert.ok(publicKeys.keys.length >= 1);",
    "cleanupJWKS();",
    "console.log('E2E_JWKS_RELOAD_OK');",
  ].join("\n");

  const secondRun = await runCommand(
    "node",
    ["-r", "tsconfig-paths/register", "-r", "@swc-node/register", "-e", reloadScript],
    {
      cwd: serverRoot,
      env: {
        ...process.env,
        NODE_ENV: "development",
        TOKEN_ENCRYPTION_KEY: tokenEncryptionKey,
        KEYS_DIR: keysDir,
      },
    },
  );

  assert.equal(secondRun.code, 0, `JWKS reload script failed\n${secondRun.output}`);
  assert.match(secondRun.output, /E2E_JWKS_RELOAD_OK/, `Expected reload marker\n${secondRun.output}`);
});
