/**
 * OpenID Connect Provider Configuration
 * Mounts oidc-provider into Express, backed by your Discord Passport auth
 *
 * oidc-provider handles the OAuth 2.0 / OIDC protocol machinery.
 * Your Discord authentication is plugged in via the interaction handler.
 */

import Provider from 'oidc-provider';
import { getDb } from '@factdb/db-core';
import { createAdapterFactory } from './adapter.ts';

export interface OidcProviderOptions {
  issuer: string; // e.g., https://fact.example.com
  baseUrl: string; // full base URL for callbacks
  jwtSigningAlg?: string;
  jwtSigningKid?: string;
}

type OidcClientConfig = {
  client_id: string;
  client_secret: string;
  redirect_uris: string[];
  response_types: string[];
  grant_types: string[];
  token_endpoint_auth_method: "none";
};

function createDefaultClientConfig(): OidcClientConfig {
  return {
    client_id: process.env.OIDC_CLIENT_ID || 'fact-index-frontend',
    client_secret: process.env.OIDC_CLIENT_SECRET || 'your-secret-change-in-prod',
    redirect_uris: [
      process.env.OIDC_FRONTEND_REDIRECT_URI || 'http://localhost:5173/oidc/callback',
    ],
    response_types: ['code', 'code id_token'],
    grant_types: ['authorization_code', 'refresh_token'],
    token_endpoint_auth_method: 'none',
  };
}

/**
 * Create an OIDC Provider instance configured for Discord-backed auth
 */
export async function createOidcProvider(opts: OidcProviderOptions): Promise<Provider> {
  const db = getDb();

  // Configure database adapter for persistent token storage
  const adapter = createAdapterFactory();
  
  const provider = new Provider(opts.issuer, {
    adapter,
    baseUrl: opts.baseUrl,

    /**
     * findAccount: Called when the OP needs to look up a user by account ID
     * In your flow, this is called with the Discord user ID after successful Discord login
     */
    async findAccount(_ctx, accountId) {
      // Load user from DB (user table, which includes imported Discord identity)
      const user = await db
        .selectFrom('user')
        .selectAll()
        .where('id', '=', accountId)
        .executeTakeFirst();

      if (!user) {
        console.log('[oidc] User not found:', accountId);
        return undefined;
      }

      return {
        accountId: user.id,

        /**
        * claims: Called to emit OIDC claims for the user
        * The 'scope' and 'claims' parameters let you see what was requested
        */
        async claims(use, scope, claims) {
          const baselineClaims: Record<string, any> = {
            sub: user.id,
            email: user.email,
            email_verified: user.emailVerified,
          };

          // Add standard profile claims if requested
          if (scope.includes('profile')) {
            baselineClaims.name = user.displayName;
            baselineClaims.preferred_username = user.displayName;
          }

          // Emit roles as custom claims for Casbin integration
          // Format: e.g., ["discord:role:123456", "local:role:admin"]
          try {
            const roles = await getUserRoles(user.id);
            baselineClaims.roles = roles;
          } catch (err) {
            console.warn('[oidc] Failed to load user roles:', err);
          }

          // Add verified_claims if Identity Assurance was requested
          // (stub for now - implement when you have a real verification process)
          if (claims?.verified_claims) {
            baselineClaims.verified_claims = {
              verification: {
                trust_framework: 'internal_loa1',
                time: new Date().toISOString(),
              },
              claims: {
                email: user.email,
              },
            };
          }

          return baselineClaims;
        },
      };
    },

    /**
     * Enable standard OIDC Claims parameter support
     * This allows RPs to request 'claims' via the authorization endpoint
     * Including verified_claims, etc.
     */
    features: {
      claimsParameter: { enabled: true },
      devInteractions: { enabled: false }, // Disabled - using custom interactions
    },

    /**
     * Configure client pre-registration
     * For federation, clients can also be discovered via federation metadata
     */
    clients: [createDefaultClientConfig()],

    // Use default key size/alg; can override in production
    jwks: {
      keys: [
        // The actual OIDC Provider JWT signing keys will be generated by oidc-provider
        // (These are different from your federation signing keys)
      ],
    },

    // Interaction configuration
    interactions: {
      url(ctx, interaction) {
        // Redirect to your login/consent flow
        return `/interaction/${interaction.uid}`;
      },
    },

    // Cookie configuration
    cookies: {
      short: { secure: process.env.NODE_ENV === 'production' },
      long: { secure: process.env.NODE_ENV === 'production' },
    },

    // Token lifetimes
    ttl: {
      AuthorizationCode: 10 * 60, // 10 minutes
      AccessToken: 1 * 60 * 60, // 1 hour
      IdToken: 1 * 60 * 60, // 1 hour
      RefreshToken: 7 * 24 * 60 * 60, // 7 days
      Session: 7 * 24 * 60 * 60, // 7 days
    },
  });

  console.log('[oidc] Provider created:', opts.issuer);
  return provider;
}

/**
 * Load user roles from DB (for Casbin integration)
 * These come from:
 * - Discord guild roles (synced during login)
 * - Local role assignments
 */
async function getUserRoles(userId: string): Promise<string[]> {
  const roles: string[] = [];

  // TODO: Implement role loading from your DB
  // For now, return empty array - fill in when you have role tables
  // Example:
  // const localRoles = await db
  //   .selectFrom('user_local_role')
  //   .select('role_key')
  //   .where('discord_user_id', '=', userId)
  //   .execute();
  // roles.push(...localRoles.map(r => `local:role:${r.role_key}`));

  return roles;
}
